### ISSUE TITLE
PUT /Settings/Default fails if QA40x window is minimized

### ISSUE THREAD

**Issue by pix64** [QuantAsylum/QA402#1]
Windows 10, 20H2
QA40x Release 0.990

1. Open QA40x Application
2. Minimize QA40x Application Window
3. Issue a /Settings/Default PUT request
4. Request returns error (400 Bad Request: Exception: (SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.))

```
curl -d "" -X PUT http://localhost:9402/Settings/Default --show-error --fail
curl: (22) The requested URL returned error: 400 Bad Request: Exception: (SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.)
```

**Comment by QuantAsylum** [comment]
Confirmed, and is fixed for 0.993. Thanks for reporting
