### ISSUE TITLE
[Request] Continuous Tone Generation via REST API

### ISSUE THREAD

**Issue by pix64** [QuantAsylum/QA402#2]
The QA401 API allows continuous tone to be generated using the GenerateToneStart and GenerateToneStop methods (earlier versions of QAAnalyzer only had a GenerateTone method w/ fixed duration). The QA40x GUI allows for a similar functionality by pressing the "Tone Gen When Idle" button, but this option is not exposed via the REST API.

**Comment by QuantAsylum** [comment]
Yes, this is a good request. Currently there is POST /AuditionStart and POST /AuditionStop. How about POST /IdleGenerationStart and POST /IdleGenerationStop? There is currently something a bit quirky with idle generation not always starting on first press. That also needs to be fixed. But be aware. We'll aim to add for 0.993

**Comment by QuantAsylum** [comment]
This is in release 0.993. It changed a bit from above. It's turned on and off like the front-panel button.

 PUT /Settings/IdleGen/On

and 

 PUT /Settings/IdleGen/Off
