### ISSUE TITLE
Cursor too slow

### ISSUE THREAD

**Issue by Opus883** [QuantAsylum/QA402#3]
The new cursor feature of the 0.999 release is very slow and it is very difficult to position the cursor at a particular frequency (e.g. with high resolution FFT).

**Comment by QuantAsylum** [comment]
This will be addressed in the release after 0.9992 with a message as shown below. Long term, this needs a decoupling between the displayed data and the captured data, where the displayed data is a decimated version that maintains max/min peaks.

![image](https://user-images.githubusercontent.com/27789827/131876138-77ff1bed-b8e0-49c0-80c8-4b8d0d72a6b6.png)
