### ISSUE TITLE
fft size for calibration verification in wiki

### ISSUE THREAD

**Issue by metebalci** [QuantAsylum/QA402#41]
In [Verifying Calibration wiki page](https://github.com/QuantAsylum/QA40x/wiki/Verifying-Calibration), it is said (in Step 2) "bump FFT to 16K" but this still gives FFT too small error. I think it should be 32k (minimum) ?

**Comment by QuantAsylum** [comment]
Yes, you are correct and thanks for noting @metebalci! The bandwidth of the expo chirp was extended a while back and that necessitates a larger FFT. I have corrected the document.
